### ISSUE TITLE
Creating the search flow 

### ISSUE THREAD

**Issue by idantb101** [FACN3/parkapp#3]
As a user, I would like to be able to find national parks in 10 secs after entering the website. 

- [x] Creating the map page and populating it with labels.
- [x] Creating the single site page. 
- [x] Creating the site list page.
